version: '3.8'
services:
  flask-app:
    build: .
    #image: maisara99/jenkins-py
    container_name: flask-app
    expose:
      - "5000"
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    depends_on:
    - flask-app
